version: "3.8"

services:
  test-nginx:
    container_name: good_cause_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - test-php-fpm
    restart: unless-stopped

  test-php-fpm:
    container_name: good_cause_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./:/app
    depends_on:
      - test-postgres
    restart: unless-stopped

  test-php-cli:
    container_name: good_cause_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - test-postgres

  test-postgres:
    container_name: good_cause_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: good_cause_network

volumes:
  postgres-db-data: